# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    serializer: ~
    indexes:
        user:
            persistence:
                driver: orm
                model: App\Domain\Entity\User
                listener:
                    insert: false
                    update: true
                    delete: true
            serializer:
                groups: [elastica]
        tweet:
            persistence:
                driver: orm
                model: App\Domain\Entity\Tweet
            serializer:
                groups: [elastica]
