# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        user:
            persistence:
                driver: orm
                model: App\Domain\Entity\User
            properties:
                login: ~
                age: ~
