security:
    password_hashers:
        App\Domain\Entity\User: auto
        Symfony\Component\Security\Core\User\InMemoryUser: plaintext

    providers:
        users_in_memory:
            memory:
                users:
                    admin:
                        password: 'my_pass'
                        roles: 'ROLE_ADMIN'
                    user:
                        password: 'other_pass'
                        roles: 'ROLE_USER'

    firewalls:
        main:
            http_basic:
            lazy: true
            provider: users_in_memory

    access_control:
        - { path: ^/api/v2/user, roles: ROLE_ADMIN, methods: [POST] }
        - { path: ^/api/doc, roles: ROLE_ADMIN }
