services:
  _defaults:
    autowire: true
    autoconfigure: true

  FeedBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'

  FeedBundle\Infrastructure\Bus\RabbitMqBus:
    calls:
      - [ 'registerProducer', [ !php/enum FeedBundle\Infrastructure\Bus\AmqpExchangeEnum::SendNotification, '@old_sound_rabbit_mq.send_notification_producer' ] ]
